### ISSUE TITLE
SD card library returns BSRR and BRR error messages

### ISSUE THREAD

**Issue by TomEngr44** [technobly/SparkCore-SD#5]
SD_CARD_LIBRARY examples Spark-DataLogger.cpp, Spark-ReadWrite.cpp and my own application files all yield the following error messages:

sd-card-library/sd2-card.cpp: In member function 'uint8_t Sd2Card::sparkSPISend(uint8_t)':

sd-card-library/sd2-card.cpp:764:40: error: 'struct GPIO_TypeDef' has no member named 'BSRR'
     PIN_MAP[mosiPin_].gpio_peripheral->BSRR = PIN_MAP[mosiPin_].gpio_pin; // Data High

sd-card-library/sd2-card.cpp:766:40: error: 'struct GPIO_TypeDef' has no member named 'BRR'
     PIN_MAP[mosiPin_].gpio_peripheral->BRR = PIN_MAP[mosiPin_].gpio_pin; // Data Low

sd-card-library/sd2-card.cpp:768:40: error: 'struct GPIO_TypeDef' has no member named 'BSRR'
    PIN_MAP[clockPin_].gpio_peripheral->BSRR = PIN_MAP[clockPin_].gpio_pin; // Clock High

sd-card-library/sd2-card.cpp:774:40: error: 'struct GPIO_TypeDef' has no member named 'BRR'
    PIN_MAP[clockPin_].gpio_peripheral->BRR = PIN_MAP[clockPin_].gpio_pin; // Clock Low

**Comment by puneetteja** [comment]
Here is the BRR & BSRR solution. Replace the code in the file "Sd2Card.cpp" with this (the original lines have been commented out and replaced with Photon compatible code):
        for (uint8_t bit = 0; bit < 8; bit++)  {
            if (data & (1 << (7-bit)))      // walks down mask from bit 7 to bit 0
                //PIN_MAP[mosiPin_].gpio_peripheral->BSRR = PIN_MAP[mosiPin_].gpio_pin; // Data High
                pinSetFast(mosiPin_);
            else
                //PIN_MAP[mosiPin_].gpio_peripheral->BRR = PIN_MAP[mosiPin_].gpio_pin; // Data Low
                pinResetFast(mosiPin_);

```
        //PIN_MAP[clockPin_].gpio_peripheral->BSRR = PIN_MAP[clockPin_].gpio_pin; // Clock High
        pinSetFast(clockPin_);

        b <<= 1;
        //if (PIN_MAP[misoPin_].gpio_peripheral->IDR & PIN_MAP[misoPin_].gpio_pin)
  if (pinReadFast(misoPin_))
            b |= 1;

        //PIN_MAP[clockPin_].gpio_peripheral->BRR = PIN_MAP[clockPin_].gpio_pin; // Clock Low
        pinResetFast(clockPin_);
    }
```

Here is an updated library: https://github.com/head-labs/sd-card-library

**Comment by TomEngr44** [comment]
Yes, thanks for the feedback. 

I found a similar solution in another thread and got the SD card routines working some time ago.

But I will review this against what I have now and keep experimenting.

Regards,

Tom Ritter
